version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    # For local testing uncomment ports. Coolify does not require ports here.
    # ports:
    #   - "3000:80"
    restart: unless-stopped
